### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vikanezrimaya** [litchipi/nix-build-templates#1]
Please include a license in your repository, so your scripts could be more easily reused without worrying about license compliance. As a suggestion, nixpkgs licenses all the `.nix` build files under [MIT license](https://github.com/nixos/nixpkgs/blob/nixos-unstable/COPYING).

**Comment by litchipi** [comment]
Yeah, that was more of a "dump" repository where I put all the recurring nix setups I use for everyday use, didn't think of that.
I just added it ! Have fun
